apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    run: books
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30020
  type: NodePort
  selector:
    app: books
