apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mysql-books
  labels:
    app: db-mysql-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mysql-books
  template:
    metadata:
      labels:
        app: db-mysql-books
    spec:
      containers:
        - name: db-mysql-books
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_DATABASE
              value: "books"
            - name: MYSQL_PASSWORD
              value: "123456"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: db-mysql-pvc-products