apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-mysql-pvc-products
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi